// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 8907ffca23
// Version Date: 2019年11月27日 星期三 21时28分21秒 UTC

// Package grpc provides a gRPC client for the Tq service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "server/proto"
	"server/service/tq-service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.TqServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var createtaskEndpoint endpoint.Endpoint
	{
		createtaskEndpoint = grpctransport.NewClient(
			conn,
			"server.Tq",
			"CreateTask",
			EncodeGRPCCreateTaskRequest,
			DecodeGRPCCreateTaskResponse,
			pb.TaskResponse{},
			clientOptions...,
		).Endpoint()
	}

	var gettaskstatusEndpoint endpoint.Endpoint
	{
		gettaskstatusEndpoint = grpctransport.NewClient(
			conn,
			"server.Tq",
			"GetTaskStatus",
			EncodeGRPCGetTaskStatusRequest,
			DecodeGRPCGetTaskStatusResponse,
			pb.TaskStatusResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		CreateTaskEndpoint:    createtaskEndpoint,
		GetTaskStatusEndpoint: gettaskstatusEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCCreateTaskResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC createtask reply to a user-domain createtask response. Primarily useful in a client.
func DecodeGRPCCreateTaskResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.TaskResponse)
	return reply, nil
}

// DecodeGRPCGetTaskStatusResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC gettaskstatus reply to a user-domain gettaskstatus response. Primarily useful in a client.
func DecodeGRPCGetTaskStatusResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.TaskStatusResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCCreateTaskRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain createtask request to a gRPC createtask request. Primarily useful in a client.
func EncodeGRPCCreateTaskRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.TaskRequest)
	return req, nil
}

// EncodeGRPCGetTaskStatusRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain gettaskstatus request to a gRPC gettaskstatus request. Primarily useful in a client.
func EncodeGRPCGetTaskStatusRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.TaskStatusRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
