FROM golang:latest

RUN apt update
RUN apt install -y software-properties-common apt-utils apt-transport-https pkg-config unzip

RUN mkdir -p /app/gomodule
COPY ./go.mod /app/gomodule

WORKDIR /app/gomodule

RUN go mod download
