// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 8907ffca23
// Version Date: 2019年11月27日 星期三 21时28分21秒 UTC

package main

import (
	"flag"
	//"log"
	// This Service
	"server/service/tq-service/svc/server"
	"server/service/tq-service/svc/slave"
  util "server/service/tq-service/util"
)

var mode = flag.String("s","master","start mode master/slave")

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()
  util.Initialize()

	if *mode == "master" {
		util.Info("start master mode.......")
		server.Run(server.DefaultConfig)
	}else{
		util.Info("start slave mode.......")
		slave.Run( )
	}
}



