// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 8907ffca23
// Version Date: 2019年11月27日 星期三 21时28分21秒 UTC

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "server/proto"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC TqServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.TqServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// tq

		createtask: grpctransport.NewServer(
			endpoints.CreateTaskEndpoint,
			DecodeGRPCCreateTaskRequest,
			EncodeGRPCCreateTaskResponse,
			serverOptions...,
		),
		gettaskstatus: grpctransport.NewServer(
			endpoints.GetTaskStatusEndpoint,
			DecodeGRPCGetTaskStatusRequest,
			EncodeGRPCGetTaskStatusResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the TqServer interface
type grpcServer struct {
	createtask    grpctransport.Handler
	gettaskstatus grpctransport.Handler
}

// Methods for grpcServer to implement TqServer interface

func (s *grpcServer) CreateTask(ctx context.Context, req *pb.TaskRequest) (*pb.TaskResponse, error) {
	_, rep, err := s.createtask.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.TaskResponse), nil
}

func (s *grpcServer) GetTaskStatus(ctx context.Context, req *pb.TaskStatusRequest) (*pb.TaskStatusResponse, error) {
	_, rep, err := s.gettaskstatus.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.TaskStatusResponse), nil
}

// Server Decode

// DecodeGRPCCreateTaskRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC createtask request to a user-domain createtask request. Primarily useful in a server.
func DecodeGRPCCreateTaskRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.TaskRequest)
	return req, nil
}

// DecodeGRPCGetTaskStatusRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC gettaskstatus request to a user-domain gettaskstatus request. Primarily useful in a server.
func DecodeGRPCGetTaskStatusRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.TaskStatusRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCCreateTaskResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain createtask response to a gRPC createtask reply. Primarily useful in a server.
func EncodeGRPCCreateTaskResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.TaskResponse)
	return resp, nil
}

// EncodeGRPCGetTaskStatusResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain gettaskstatus response to a gRPC gettaskstatus reply. Primarily useful in a server.
func EncodeGRPCGetTaskStatusResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.TaskStatusResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
